packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
      react-dom: '*'
  '@apollo/link-error@*':
    dependencies:
      graphql: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/link-schema@*':
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/react-ssr@*':
    dependencies:
      graphql: '*'
      react: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
      next: 10.0.5
  '@emotion/react@*':
    dependencies:
      react: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
      react: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20220605.hash-c4f9c8f.cjs
