packageExtensions:
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      next: 10.0.5
      '@types/zen-observable': '*'
  '@apollo/client@*':
    dependencies:
      react-dom: '*'
      '@types/zen-observable': '*'
  '@apollo/link-schema@*':
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/link-error@*':
    dependencies:
      graphql: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/react-ssr@*':
    dependencies:
      react: '*'
      graphql: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
      react: '*'
  '@emotion/react@*':
    dependencies:
      react: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'

plugins:
  - path: .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
