packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
      react-dom: '*'
  '@apollo/link-error@*':
    dependencies:
      graphql: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/link-schema@*':
    peerDependencies:
      '@apollo/client': '*'
  '@apollo/react-ssr@*':
    dependencies:
      graphql: '*'
      react: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@atls-ui-parts/carousel@*':
    dependencies:
      '@atls-ui-parts/dom': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
      next: 10.0.5
  '@emotion/react@*':
    dependencies:
      react: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
      react: '*'
  '@react-three/drei@*':
    dependencies:
      three-stdlib: 'patch:three-stdlib@npm%3A2.28.9#~/.yarn/patches/three-stdlib-npm-2.28.9-598c595c00.patch'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'
  swiper@*:
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
