enableGlobalCache: false

packageExtensions:
  '@graphql-codegen/plugin-helpers@*':
    dependencies:
      '@graphql-tools/apollo-engine-loader': '8.0.1'
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    dependencies:
      graphql: '*'
      react: '*'
    peerDependencies:
      '@apollo/client': '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@emotion/react@*':
    dependencies:
      react: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'
      react: '*'
  '@react-three/drei@*':
    dependencies:
      three-stdlib: 'patch:three-stdlib@npm%3A2.28.9#~/.yarn/patches/three-stdlib-npm-2.28.9-598c595c00.patch'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  framer-motion@*:
    dependencies:
      csstype: '*'
  swiper@*:
    dependencies:
      react: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
