packageExtensions:
  '@atls/next-app-with-apollo@*':
    dependencies:
      next: 10.0.5
  '@apollo/client@*':
    dependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    dependencies:
      graphql: '*'
  '@apollo/react-ssr@*':
    dependencies:
      react: '*'

plugins:
  - path: .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.0-rc.5.cjs
