version: '3.8'

services:
  yarn:
    image: node:16
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  landing:
    image: node:16
    volumes:
      - ./:/workspace
    working_dir: /workspace
    entrypoint: yarn workspace @landing/renderer-entrypoint dev
    ports:
      - "3000:3000"
