export * from './primary-colors.styles'
export * from './secondary-colors.styles'
export * from './tertiary-colors.styles'
export * from './transparent-colors.styles'
export * from './clipboard-colors.styles'
