name: Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn workspace @landing/app prepack

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: 37.140.192.245
          username: u1055818_dt
          local-dir: "./dt-next"
          password: ${{ secrets.ftp_password }}
